swagger: "2.0"
info:
  version: "0.0.1"
  title: API Real Estate
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  
  # Pattern API
  /Pattern:
    x-swagger-router-controller: patterns_controller
    get:
      summary: Lấy hết tất cả patterns
      description: Lấy hết tất cả patterns hiện có trong database
      operationId: getAllPatterns
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PatternsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: Thêm pattern mới
      description: Thêm mới 1 pattern
      operationId: insertPattern
      parameters:
        - name: patternCategoryID
          in: body
          required: true
          schema:
            $ref: "#/definitions/Patterns"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /Pattern/FindBy:
    x-swagger-router-controller: patterns_controller
    get:
      summary: Tìm pattern theo tiêu chí
      description: Tìm pattern theo từng tiêu chí.
      operationId: getPatternsByID
      parameters:
        - name: "typeQuery"
          type: "integer"
          maximum: 4
          in: "query"
          required: true
          description: "Find By: 1 - patternID,\r\n 2 - SiteID,\r\n 3 - PatternCategoryID,\r\n 4 - SiteID and PatternCategoryID"
        - name: "values"
          in: "query"
          required: true
          type: "array"
          items:
            type: "string"
          description: "Mảng giá trị truyền vào phụ thuộc vào typeQuery"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PatternsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /Pattern/{patternID}:
    x-swagger-router-controller: patterns_controller
    get:
      summary: Lấy ra pattern theo patternID
      description: Lấy ra pattern theo patternID
      parameters:
        - name: patternID
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Patterns"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      operationId: updatePatterns
      summary: Cập nhật pattern
      description: Cập nhật pattern theo patternID
      parameters:
        - name: patternID
          in: path
          required: true
          type: number
        - name: payload
          in: body
          required: true
          schema:
            $ref: "#/definitions/Patterns"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      operationId: deletePatterns
      summary: Xóa pattern
      description: Xóa pattern theo patternID
      parameters:
        - name: patternID
          in: path
          required: true
          type: number
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  #Site API
  /Site:
    x-swagger-router-controller: sites_controller
    get:
      summary: Lấy hết tất cả sites 
      description: Lấy tất cả sites có trong database
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SitesResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: Thêm site mới
      description: Thêm mới 1 site
      parameters:
        - name: "payload"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/SiteURLRequest"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      
  /Site/{siteID}:
    x-swagger-router-controller: sites_controller
    get:
      summary: Lấy ra site theo siteID
      description: Lấy ra site theo siteID
      parameters:
        - name: siteID
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SitesResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    
    put:
      summary: Cập nhật site
      description: Cập nhật site theo siteID
      parameters:
        - name: siteID
          in: path
          required: true
          type: number
        - name: payload
          in: body
          required: true
          schema:
            $ref: "#/definitions/SitesResponse"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      summary: Xóa site
      description: Xóa site theo siteID
      parameters:
        - name: siteID
          in: path
          required: true
          type: number
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"        
  
  # Crawler API
  /Crawler/CollectDetailURL:
    x-swagger-router-controller: crawler_controller
    get:
      description: "Lấy URL chi tiết của 1 page bds"
      parameters:
        - name: categoryURL
          in: query
          type: string
          required: true
        - name: patternURL
          in: query
          type: string
          required: true
        - name: typePage
          in: query
          type: string
          required: true
        - name: pageLimit
          in: query
          type: number
          required: false
        
      responses:
        "200":
          description: "Lấy URL thành công"
          schema:
            $ref: "#/definitions/CrawlerResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /Crawler/CollectDetailURLBySiteID:
    x-swagger-router-controller: crawler_controller
    get:
      description: "Lấy URL bài viết của tất cả các link có trong siteID"
      operationId: getURLBySiteID
      parameters:
        - name: siteID
          in: query
          type: number
          required: true
        - name: pageLimit
          in: query
          type: number
          required: false
        
      responses:
        "200":
          description: "Lấy URL thành công"
          schema:
            $ref: "#/definitions/CrawlerResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
            
    #User API       
  
  #User API
  /User:
    x-swagger-router-controller: user_controller
    get:
      operationId: getAllUsers
      summary: Lấy hết tất cả user
      description: Lấy hết tất cả user hiện có trong database
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: insertUser
      summary: Thêm user mới
      description: Thêm mới 1 user vào database
      parameters:
        - name: payload
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/UsersRequire"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /User/{userID}:
    x-swagger-router-controller: user_controller
    get:
      operationId: getUserByID
      summary: Lấy ra user theo userID
      description: Lấy ra user theo userID
      parameters:
        - name: userID
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      operationId: updateUser
      summary: Cập nhật user
      description: Cập nhật user theo userID
      parameters:
        - name: userID
          in: path
          required: true
          type: number
        - name: payload
          in: body
          required: true
          schema:
            $ref: "#/definitions/UsersRequire"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      operationId: deleteUser
      summary: Xóa user
      description: Xóa user theo userID
      parameters:
        - name: userID
          in: path
          required: true
          type: number
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  #Pattern_Categories API
  /Patt_Category:
    x-swagger-router-controller: patterncategory_controller
    get:
      summary: Lấy hết tất cả pattern_categories
      description: Lấy tất cả pattern_categories có trong database
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PatternCatergories"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: Thêm site mới
      description: Thêm mới 1 site
      parameters:
        - name: payload
          in: body
          required: true
          schema:
            $ref: "#/definitions/PatternCatergories"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
            
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description
  CrawlerResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      data:
        type: array
        items:
          type: string
          description: "Mảng URL được lấy về"
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description
  Patterns:
    type: object
    properties:
      patternCategoryId:
        type: number
        description: ID của pattern categories
      patternRegex:
        type: string
        description: Chuỗi regular expression cần thêm vào 
      siteId:
        type: number
        description: ID của site cần thêm vào
    required:
      - patternCategoryId
      - patternRegex
      - siteId
  SitesResponse:
    type: object
    properties:
      siteID:
        type: number
      siteName:
        type: string
      siteURL:
        type: string
      description:
        type: string
        description: Mo ta
      
  PatternsResponse:
    required:
      - patterns
    properties:
      sucess:
        type: number
        description: Tra ve 1 neu thanh cong, Tra ve 0 neu that bai
      patterns:
        type: array
        items:
          type: object
          properties:
            patternId:
              type: number
            patternCategoryId:
              type: number
            patternRegex:
              type: string
            patternCategoryName:
              type: string
            siteId:
              type: number
      description:
        type: string
        description: Mo ta
        
  SiteURLRequest:
    type: object
    properties:
      siteName:
        type: string
        description: "Tên site cần thêm vào"
      siteURL:
        type: object
        properties:
          site_name:
            type: string
            description: Tên site cần thêm vào
          site_url:
            type: string
            description: url của site cần thêm vào 
          site_url_categories:
            type: array
            description: Mảng các các url
            items:
              type: object
              properties:
                category_name:
                  type: string
                  description: Tên danh mục của url cần thêm
                category_url:
                  type: string
                  description: url của danh mục
          type_page_url:
            type: string
            description: Loại trang khi chuyển sang trang khác      
    required:
      - siteName
      - siteURL
      
  UserResponse:
    type: object
    properties:
      userID:
        type: number
        description: id của người dùng
      userName:
        type: string
        description: tên của người dùng
      userPassword:
        type: string
        description: password của người dùng
      userStatus:
        type: string
        description: Mô tả tinh trạng của user
        
  UsersRequire:
    required:
      - userName
      - userPassword
    type: object
    properties:
      userName:
        type: string
        description: Tên của người dùng
      userPassword:
        type: string
        description: password của người dùng
  
  PatternCatergories:
    type: object
    properties:
      patthCategoryID:
        type: number
        description: id của người dùng
      patthCategoryName:
        type: string
        description: tên của người dùng

    
  
      
