swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /Pattern:
    x-swagger-router-controller: patterns_controller
    get:
      summary: Lấy hết tất cả patterns
      description: Lấy hết tất cả patterns hiện có trong database
      operationId: getAllPatterns
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PatternsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      summary: Thêm pattern mới
      description: Thêm mới 1 pattern
      parameters:
        - name: patternCategoryID
          in: body
          required: true
          schema:
            $ref: "#/definitions/Patterns"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /Pattern/FindBy:
    x-swagger-router-controller: patterns_controller
    get:
      summary: Tìm pattern theo tiêu chí
      description: Tìm pattern theo từng tiêu chí.
      parameters:
        - name: "typeQuery"
          type: "number"
          in: "query"
          required: true
          description: "Find By: 0 - patternID,\r\n 1 - SiteID,\r\n 2 - PatternCategoryID,\r\n 3 - SiteID and PatternCategoryID"
        - name: "values"
          in: "query"
          required: true
          type: "array"
          items:
            type: "string"
          description: "Mảng giá trị truyền vào phụ thuộc vào typeQuery"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/PatternsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /Pattern/{patternID}:
    x-swagger-router-controller: patterns_controller
    get:
      summary: Lấy ra pattern theo patternID
      description: Lấy ra pattern theo patternID
      parameters:
        - name: patternID
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Patterns"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      summary: Cập nhật pattern
      description: Cập nhật pattern theo patternID
      parameters:
        - name: patternID
          in: path
          required: true
          type: number
        - name: patternCategoryID
          in: body
          required: true
          schema:
            $ref: "#/definitions/Patterns"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      summary: Xóa pattern
      description: Xóa pattern theo patternID
      parameters:
        - name: patternID
          in: path
          required: true
          type: number
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description
  Patterns:
    type: object
    properties:
      patternCategoryId:
        type: number
        description: ID của pattern categories
      patternRegex:
        type: string
        description: Chuỗi regular expression cần thêm vào 
      siteId:
        type: number
        description: ID của site cần thêm vào
    required:
      - patternCategoryId
      - patternRegex
      - siteId
  PatternsResponse:
    required:
      - patterns
    properties:
      sucess:
        type: number
        description: Tra ve 1 neu thanh cong, Tra ve 0 neu that bai
      patterns:
        type: array
        items:
          type: object
          properties:
            patternId:
              type: number
            patternCategoryId:
              type: number
            patternRegex:
              type: string
            patternCategoryName:
              type: string
            siteId:
              type: number
      description:
        type: string
        description: Mo ta
      
      
